# Q.1

In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

inputs = np.array([[0.3, 0.8]])
outputs = np.array([[0.05, 0.6]])

np.random.seed(0)  
input_weights = np.random.rand(2, 2)  
hidden_weights = np.random.rand(2, 2) 
input_bias = np.ones((1, 2))
hidden_bias = np.ones((1, 2))

learning_rates = [0.5, 0.1, 0.01]

for learning_rate in learning_rates:
    print(f"Training with learning rate: {learning_rate}")
    
    for epoch in range(100):
        input_layer = inputs
        hidden_layer_input = np.dot(input_layer, input_weights) + input_bias
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, hidden_weights) + hidden_bias
        output_layer_output = sigmoid(output_layer_input)

        error = outputs - output_layer_output
        d_output = error * sigmoid_derivative(output_layer_output)

        error_hidden = d_output.dot(hidden_weights.T)
        d_hidden = error_hidden * sigmoid_derivative(hidden_layer_output)

        hidden_weights += hidden_layer_output.T.dot(d_output) * learning_rate
        input_weights += input_layer.T.dot(d_hidden) * learning_rate
        hidden_bias += np.sum(d_output, axis=0, keepdims=True) * learning_rate
        input_bias += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

    print("Final output after training:")
    print(output_layer_output)
    print("\n")

Training with learning rate: 0.5
Final output after training:
[[0.10017055 0.60207291]]


Training with learning rate: 0.1
Final output after training:
[[0.09140714 0.60051907]]


Training with learning rate: 0.01
Final output after training:
[[0.09065024 0.60045178]]




# Q.2

In [2]:
import numpy as np
#!pip install tensorflow
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Input(2),
    layers.Dense(2, activation='sigmoid', use_bias=True, bias_initializer='ones', name='hidden_layer'),
    layers.Dense(2, activation='sigmoid', use_bias=True, bias_initializer='ones', name='output_layer')
])

learning_rates = [0.5, 0.1, 0.01]
for lr in learning_rates:
    optimizer = keras.optimizers.SGD(learning_rate=lr)
    model.compile(optimizer=optimizer, loss='mean_squared_error')

    history = model.fit(np.array([[0.3, 0.8]]), np.array([[0.05, 0.6]]), epochs=100, verbose=0)

    output = model.predict(np.array([[0.3, 0.8]]))
    print(f"Learning rate: {lr}")
    print("Final output after training:")
    print(output)
    print("\n")

C:\Users\athar\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


1/1 [==============================] - 0s 97ms/step
Learning rate: 0.5
Final output after training:
[[0.09856268 0.59978354]]


1/1 [==============================] - 0s 62ms/step
Learning rate: 0.1
Final output after training:
[[0.09061114 0.59985816]]


1/1 [==============================] - 0s 49ms/step
Learning rate: 0.01
Final output after training:
[[0.08994644 0.59986264]]




In [1]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')


[]

In [2]:
import tensorflow as tf

# List all available physical devices (including GPUs)
physical_devices = tf.config.list_physical_devices()
print("Available Physical Devices:", physical_devices)

# List GPUs specifically
gpus = tf.config.list_physical_devices('GPU')
print("Available GPUs:", gpus)


Available Physical Devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Available GPUs: []


In [3]:
pip install tensorflow-gpu

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [18 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\athar\AppData\Local\Temp\pip-install-pfi0kgvd\tensorflow-gpu_97851875a84d4a57b694778e5470932f\setup.py", line 37, in <module>
      raise Exception(TF_REMOVAL_WARNING)
  Exception:
  
  The "tensorflow-gpu" package has been removed!
  
  Please install "tensorflow" instead.
  
  Other than the name, the two packages have been identical
  since TensorFlow 2.1, or roughly since Sep 2019. For more
  information, see: pypi.org/project/tensorflow-gpu
  
  
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
ERROR: Could not build wheels for tensorflow-gpu, which is required to install pyproject.toml-

In [5]:
pip install tensorflow



[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import tensorflow as tf

# List all available physical devices (including GPUs)
physical_devices = tf.config.list_physical_devices()
print("Available Physical Devices:", physical_devices)

# List GPUs specifically
gpus = tf.config.list_physical_devices('GPU')
print("Available GPUs:", gpus)


Available Physical Devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Available GPUs: []
